// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package dbgen

import (
	"database/sql"
)

type Book struct {
	ID          int64
	Name        string
	ReleaseYear int64
	TotalPage   int64
}

type BookCategory struct {
	ID         int64
	BookID     sql.NullInt64
	CategoryID sql.NullInt64
}

type Category struct {
	ID   int64
	Name string
}
